module.exports = {
  CHIRP: 'CHIRP',
  CHIRPED: 'CHIRPED',
  GOT_CHIRPS: 'GOT_CHIRPS',

  GOT_CURRENT_USER: 'GOT_CURRENT_USER',
  GOT_USERS: 'GOT_USERS',

  FOLLOW: 'FOLLOW',
  FOLLOWED: 'FOLLOWED',

  UNFOLLOW: 'FOLLOW',
  UNFOLLOWED: 'FOLLOWED',
};